version: '3.8'

services:
  web:
    build: .
    container_name: iot-door-lock-web
    ports:
      - "8080:80"
    volumes:
      - ./src/php/:/var/www/html/
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=rfid_access

  db:
    image: mysql:8.0
    container_name: iot-door-lock-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: rfid_access
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  db_data: